name: llm4r
channels:
  - pytorch
  - nvidia
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=5.1=1_gnu
  - blas=1.0=mkl
  - bzip2=1.0.8=h7b6447c_0
  - ca-certificates=2023.12.12=h06a4308_0
  - certifi=2024.2.2=py312h06a4308_0
  - charset-normalizer=2.0.4=pyhd3eb1b0_0
  - cuda-cudart=12.1.105=0
  - cuda-cupti=12.1.105=0
  - cuda-libraries=12.1.0=0
  - cuda-nvrtc=12.1.105=0
  - cuda-nvtx=12.1.105=0
  - cuda-opencl=12.3.101=0
  - cuda-runtime=12.1.0=0
  - expat=2.5.0=h6a678d5_0
  - ffmpeg=4.3=hf484d3e_0
  - filelock=3.13.1=py312h06a4308_0
  - freetype=2.12.1=h4a9f257_0
  - gmp=6.2.1=h295c915_3
  - gnutls=3.6.15=he1e5248_0
  - idna=3.4=py312h06a4308_0
  - intel-openmp=2023.1.0=hdb19cb5_46306
  - jinja2=3.1.3=py312h06a4308_0
  - jpeg=9e=h5eee18b_1
  - lame=3.100=h7b6447c_0
  - lcms2=2.12=h3be6417_0
  - ld_impl_linux-64=2.38=h1181459_1
  - lerc=3.0=h295c915_0
  - libcublas=12.1.0.26=0
  - libcufft=11.0.2.4=0
  - libcufile=1.8.1.2=0
  - libcurand=10.3.4.107=0
  - libcusolver=11.4.4.55=0
  - libcusparse=12.0.2.55=0
  - libdeflate=1.17=h5eee18b_1
  - libffi=3.4.4=h6a678d5_0
  - libgcc-ng=11.2.0=h1234567_1
  - libgomp=11.2.0=h1234567_1
  - libiconv=1.16=h7f8727e_2
  - libidn2=2.3.4=h5eee18b_0
  - libjpeg-turbo=2.0.0=h9bf148f_0
  - libnpp=12.0.2.50=0
  - libnvjitlink=12.1.105=0
  - libnvjpeg=12.1.1.14=0
  - libpng=1.6.39=h5eee18b_0
  - libstdcxx-ng=11.2.0=h1234567_1
  - libtasn1=4.19.0=h5eee18b_0
  - libtiff=4.5.1=h6a678d5_0
  - libunistring=0.9.10=h27cfd23_0
  - libuuid=1.41.5=h5eee18b_0
  - libwebp-base=1.3.2=h5eee18b_0
  - llvm-openmp=14.0.6=h9e868ea_0
  - lz4-c=1.9.4=h6a678d5_0
  - markupsafe=2.1.3=py312h5eee18b_0
  - mkl=2023.1.0=h213fc3f_46344
  - mkl-service=2.4.0=py312h5eee18b_1
  - mkl_fft=1.3.8=py312h5eee18b_0
  - mkl_random=1.2.4=py312hdb19cb5_0
  - mpmath=1.3.0=py312h06a4308_0
  - ncurses=6.4=h6a678d5_0
  - nettle=3.7.3=hbbd107a_1
  - networkx=3.1=py312h06a4308_0
  - numpy=1.26.4=py312hc5e2394_0
  - numpy-base=1.26.4=py312h0da6c21_0
  - openh264=2.1.1=h4ff587b_0
  - openjpeg=2.4.0=h3ad879b_0
  - openssl=3.0.13=h7f8727e_0
  - pillow=10.2.0=py312h5eee18b_0
  - pip=23.3.1=py312h06a4308_0
  - python=3.12.0=h996f2a0_0
  - pytorch=2.2.1=py3.12_cuda12.1_cudnn8.9.2_0
  - pytorch-cuda=12.1=ha16c6d3_5
  - pytorch-mutex=1.0=cuda
  - pyyaml=6.0.1=py312h5eee18b_0
  - readline=8.2=h5eee18b_0
  - requests=2.31.0=py312h06a4308_1
  - setuptools=68.2.2=py312h06a4308_0
  - sqlite=3.41.2=h5eee18b_0
  - sympy=1.12=py312h06a4308_0
  - tbb=2021.8.0=hdb19cb5_0
  - tk=8.6.12=h1ccaba5_0
  - torchaudio=2.2.1=py312_cu121
  - torchvision=0.17.1=py312_cu121
  - typing_extensions=4.9.0=py312h06a4308_1
  - urllib3=2.1.0=py312h06a4308_0
  - wheel=0.41.2=py312h06a4308_0
  - xz=5.4.5=h5eee18b_0
  - yaml=0.2.5=h7b6447c_0
  - zlib=1.2.13=h5eee18b_0
  - zstd=1.5.5=hc292b87_0
  - pip:
      - aiohttp==3.9.3
      - aiosignal==1.3.1
      - annotated-types==0.6.0
      - anyio==4.3.0
      - argon2-cffi==23.1.0
      - argon2-cffi-bindings==21.2.0
      - arrow==1.3.0
      - asttokens==2.4.1
      - async-lru==2.0.4
      - attrs==23.2.0
      - babel==2.14.0
      - beautifulsoup4==4.12.3
      - bleach==6.1.0
      - cffi==1.16.0
      - comm==0.2.1
      - contourpy==1.2.0
      - cycler==0.12.1
      - dataclasses-json==0.6.4
      - debugpy==1.8.1
      - decorator==5.1.1
      - defusedxml==0.7.1
      - distro==1.9.0
      - executing==2.0.1
      - fastjsonschema==2.19.1
      - fireworks-ai==0.13.0
      - fonttools==4.49.0
      - fqdn==1.5.1
      - frozenlist==1.4.1
      - fsspec==2024.3.1
      - greenlet==3.0.3
      - h11==0.14.0
      - httpcore==1.0.4
      - httpx==0.27.0
      - httpx-sse==0.4.0
      - huggingface-hub==0.22.2
      - ipykernel==6.29.3
      - ipython==8.22.1
      - ipywidgets==8.1.2
      - isoduration==20.11.0
      - jedi==0.19.1
      - joblib==1.3.2
      - json5==0.9.17
      - jsonpatch==1.33
      - jsonpointer==2.4
      - jsonschema==4.21.1
      - jsonschema-specifications==2023.12.1
      - jupyter==1.0.0
      - jupyter-client==8.6.0
      - jupyter-console==6.6.3
      - jupyter-core==5.7.1
      - jupyter-events==0.9.0
      - jupyter-lsp==2.2.3
      - jupyter-server==2.12.5
      - jupyter-server-terminals==0.5.2
      - jupyterlab==4.0.10
      - jupyterlab-pygments==0.3.0
      - jupyterlab-server==2.25.3
      - jupyterlab-widgets==3.0.10
      - kiwisolver==1.4.5
      - langchain==0.1.0
      - langchain-community==0.0.20
      - langchain-core==0.1.36
      - langchain-fireworks==0.1.1
      - langsmith==0.1.38
      - marshmallow==3.21.0
      - matplotlib==3.8.3
      - matplotlib-inline==0.1.6
      - mistune==3.0.2
      - multidict==6.0.5
      - mypy-extensions==1.0.0
      - nbclient==0.9.0
      - nbconvert==7.16.1
      - nbformat==5.9.2
      - nest-asyncio==1.6.0
      - notebook==7.0.8
      - notebook-shim==0.2.4
      - openai==1.14.3
      - orjson==3.10.0
      - overrides==7.7.0
      - packaging==23.2
      - pandas==2.1.4
      - pandocfilters==1.5.1
      - parso==0.8.3
      - pexpect==4.9.0
      - platformdirs==4.2.0
      - prometheus-client==0.20.0
      - prompt-toolkit==3.0.43
      - psutil==5.9.8
      - ptyprocess==0.7.0
      - pure-eval==0.2.2
      - pycparser==2.21
      - pydantic==2.6.2
      - pydantic-core==2.16.3
      - pygments==2.17.2
      - pyparsing==3.1.1
      - python-dateutil==2.8.2
      - python-json-logger==2.0.7
      - pytz==2024.1
      - pyzmq==25.1.2
      - qtconsole==5.5.1
      - qtpy==2.4.1
      - referencing==0.33.0
      - replicate==0.25.1
      - rfc3339-validator==0.1.4
      - rfc3986-validator==0.1.1
      - rpds-py==0.18.0
      - scikit-learn==1.4.1.post1
      - scipy==1.12.0
      - seaborn==0.13.1
      - send2trash==1.8.2
      - six==1.16.0
      - sniffio==1.3.1
      - soupsieve==2.5
      - sqlalchemy==2.0.27
      - stack-data==0.6.3
      - tenacity==8.2.3
      - terminado==0.18.0
      - text-generation==0.7.0
      - threadpoolctl==3.3.0
      - tinycss2==1.2.1
      - tornado==6.4
      - tqdm==4.66.2
      - traitlets==5.14.1
      - types-python-dateutil==2.8.19.20240106
      - typing-inspect==0.9.0
      - tzdata==2024.1
      - uri-template==1.3.0
      - wcwidth==0.2.13
      - webcolors==1.13
      - webencodings==0.5.1
      - websocket-client==1.7.0
      - widgetsnbextension==4.0.10
      - yarl==1.9.4
prefix: /storage/rvacareanu/apps/miniconda3/envs/llm4r
